// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoPlayController from "./auto_play_controller"
application.register("auto-play", AutoPlayController)

import DialogController from "./dialog_controller"
application.register("dialog", DialogController)

import FeedDrawerController from "./feed_drawer_controller"
application.register("feed-drawer", FeedDrawerController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LocationSelectionController from "./location_selection_controller"
application.register("location-selection", LocationSelectionController)

import OfflineAlertController from "./offline_alert_controller"
application.register("offline-alert", OfflineAlertController)

import RummyTurnController from "./rummy_turn_controller"
application.register("rummy-turn", RummyTurnController)

import ServiceWorkerController from "./service_worker_controller"
application.register("service-worker", ServiceWorkerController)

import TimerController from "./timer_controller"
application.register("timer", TimerController)
